name: Daily Dress Scraper

on:
  schedule:
    - cron: '0 10 * * *'  # 6AM EST (10AM UTC)
  workflow_dispatch:      # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run scraper
        run: python asos_scraper.py

      - name: Commit and push updated dresses.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add dresses.json
          git commit -m "Update dresses.json from ASOS scraper" || echo "No changes to commit"
          git push
